language: rust
cache: cargo
rust:
  - stable
before_install:
  # Binary dependencies
  - sudo apt-get -qq update
  - sudo apt-get install -y libopenal-dev libsndfile1-dev
  # gstreamer >= 1.8
  - sudo apt-get install -y autoconf automake autopoint libtool
  - for x in gstreamer gst-plugins-base gst-plugins-good gst-plugins-ugly gst-plugins-bad; do git clone git://anongit.freedesktop.org/gstreamer/$x; cd $x; ./autogen.sh > /dev/null; ./configure > /dev/null; make > /dev/null; sudo make install > /dev/null; cd ..; done
