[package]
authors = ["jD91mZM2 <me@krake.one>"]
description = "Play images/videos in your terminal"
name = "termplay"
version = "2.0.0"
[dependencies]
image = "0.18.0"

[dependencies.ears]
optional = true
version = "0.5.1"

[dev-dependencies]
clap = "2.31.2"
failure = "0.1.1"
termion = "1.5.1"

[features]
default = ["ears"]
