[package]
name = "termplay"
version = "0.1.0"
description = "Play an image/video in your terminal!"
repository = "https://github.com/legolord208/termplay"
authors = ["LEGOlord208 <LEGOlord208@krake.one>"]
license = "MIT"

[dependencies]
tempdir = "0.3"
clap = "2.24"
ctrlc = "3.0"
image = "0.14"
terminal_size = "0.1"
lazy_static = "0.2"
time = "0.1"
ears = "0.4"
sixel-sys = "0.2"
