[package]
name = "termplay"
version = "1.1.3"
description = "Play an image/video in your terminal!"
repository = "https://github.com/legolord208/termplay"
authors = ["jD91mZM2 <me@krake.one>"]
license = "MIT"

[dependencies]
tempdir = "0.3"
clap = "2.24"
ctrlc = "3.0"
image = "0.14"
lazy_static = "0.2"
time = "0.1"
ears = "0.4"
sixel-sys= { version = "0.2", optional = true }
termion = "1.4"

[features]

default = ["screen", "sixel-sys"]
screen  = []
