[package]
name = "termplay"
version = "1.2.0"
description = "Play an image/video in your terminal!"
repository = "https://github.com/legolord208/termplay"
authors = ["jD91mZM2 <me@krake.one>"]
license = "MIT"

[dependencies]
clap = "2.24"
ctrlc = { version = "3.0", optional = true, features = ["termination"] }
ears = { version = "0.4", optional = true }
image = "0.14"
lazy_static = "0.2"
redox_syscall = { version = "0.1", optional = true }
sixel-sys = { version = "0.2", optional = true }
tempdir = "0.3"
termion = "1.4"
time = "0.1"

[features]

default = ["ctrlc", "ears", "screen", "sixel-sys"]
screen  = []
screen_control = []
