[package]
authors = ["jD91mZM2 <me@krake.one>"]
description = "Play an image/video in your terminal!"
license = "MIT"
name = "termplay"
repository = "https://github.com/legolord208/termplay"
version = "1.2.0"
[dependencies]
clap = "2.29.0"
image = "0.18.0"
lazy_static = "1.0.0"
tempdir = "0.3.5"
termion = "1.5.1"
time = "0.1.39"

[dependencies.ctrlc]
features = ["termination"]
optional = true
version = "3.0.3"

[dependencies.ears]
optional = true
version = "0.4.0"

[dependencies.redox_syscall]
optional = true
version = "0.1.31"

[dependencies.sixel-sys]
optional = true
version = "0.3.1"

[features]
default = ["ctrlc", "ears", "screen", "sixel-sys"]
screen = []
screen_control = []
